export enum EAdminNavigation {
  dashboard = '/admin/dashboard',
  authLogin = '/admin/auth/login',
  authLogout = '/admin/auth/logout',
  users = '/admin/users',
  usersCreate = '/admin/users/new',
  customers = '/admin/customers',
  customersCreate = '/admin/customers/new',
  products = '/admin/products',
  productsCreate = '/admin/products/new',
  categories = '/admin/products/categories',
  categoriesCreate = '/admin/products/categories/new',
  orders = '/admin/orders',
  carts = '/admin/carts',
}
